[package]
name = "r3dgd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.7"
flate2 = "1.0.28"
xml-rs = "0.8.19"
